---
kind: pipeline
type: docker
name: squid arm32
platform:
  os: linux
  arch: arm
steps:
- name: docker
  image: plugins/docker
  settings:
    repo: b4tman/squid
    tags: "${DRONE_COMMIT_SHA}-armhf"
    dry_run: true
trigger:
  branch:
    - master
