---
kind: pipeline
type: docker
name: arm32 images
platform:
  os: linux
  arch: arm
steps:
- name: squid image for dockerhub
  image: plugins/docker
  settings:
    repo: b4tman/squid
    auto_tag: true
    auto_tag_suffix: armhf
    pull_image: true
    username:
      from_secret: dockerhub_login
    password:
      from_secret: dockerhub_token
- name: squid image for github packages
  image: plugins/docker
  settings:
    repo: docker.pkg.github.com/b4tman/docker-squid/squid
    auto_tag: true
    auto_tag_suffix: armhf
    pull_image: true
    registry: docker.pkg.github.com
    username:
      from_secret: github_login
    password:
      from_secret: github_token
trigger:
  ref:
  - refs/tags/**
  - refs/heads/master
